/**
 * Turning commits into the lines the "what's new" panel shows.
 *
 * Shared by the two things that write changelog.generated.ts: the manual
 * `npm run changelog`, which reads a full local history, and the step at the
 * start of every Vercel build, which reads whatever that build can see and
 * adds it to the committed list. Kept free of I/O so both -- and the tests --
 * use exactly the same rules.
 *
 * Two rules make the result worth reading rather than merely automatic:
 *
 * - Only `feat:` and `fix:` appear. A `docs:`, `chore:`, `test:` or `refactor:`
 *   commit changed nothing the lab can see.
 * - The Thai line comes from a `Changelog-TH:` trailer on the commit, and
 *   falls back to the English subject -- which is the nudge to add one.
 */

import type { ChangeEntry } from './changelog';

/** The `Changelog-TH:` trailer, if the commit carries one. */
export function thaiTrailer(body: string): string {
  for (const line of body.split('\n')) {
    const match = /^Changelog-TH:\s*(.+?)\s*$/.exec(line);
    if (match) return match[1];
  }
  return '';
}

/** One commit as a changelog line, or null for a commit the lab cannot see. */
export function entryFrom(date: string, subject: string, body: string): ChangeEntry | null {
  // `feat!:` is still a feature as far as the lab is concerned.
  const match = /^(feat|fix)!?:\s*(.+)$/.exec(subject.trim());
  if (!match) return null;
  const [, type, text] = match;
  return { date, kind: type === 'feat' ? 'new' : 'fix', th: thaiTrailer(body) || text, en: text };
}

// Unit and record separators, as characters rather than literal bytes: git
// writes them through its own `%x1f` / `%x1e` escapes in the format string.
export const FIELD_SEP = String.fromCharCode(31);
export const RECORD_SEP = String.fromCharCode(30);

/** Output of `git log --pretty=format:%ad%x1f%s%x1f%b%x1e`, newest first. */
export function entriesFromGitLog(log: string): ChangeEntry[] {
  const entries: ChangeEntry[] = [];
  for (const record of log.split(RECORD_SEP)) {
    const [date, subject, body = ''] = record.replace(/^\n+/, '').split(FIELD_SEP);
    if (!date || !subject) continue;
    const entry = entryFrom(date, subject, body);
    if (entry) entries.push(entry);
  }
  return entries;
}

/** The shape GitHub's list-commits API returns, as far as this reads it. */
export type ApiCommit = { commit: { message: string; author: { date: string } | null } };

/**
 * GitHub's list of commits, newest first. `dayOf` turns the author's instant
 * into the lab's calendar day, which is what `git log --date=short` gives for
 * commits made in Bangkok.
 */
export function entriesFromApi(commits: ApiCommit[], dayOf: (iso: string) => string): ChangeEntry[] {
  const entries: ChangeEntry[] = [];
  for (const { commit } of commits) {
    if (!commit?.author?.date || typeof commit.message !== 'string') continue;
    const [subject, ...rest] = commit.message.split('\n');
    const entry = entryFrom(dayOf(commit.author.date), subject, rest.join('\n'));
    if (entry) entries.push(entry);
  }
  return entries;
}

const keyOf = (e: ChangeEntry) => `${e.kind}|${e.en}|${e.th}`;

/**
 * The committed list, plus whatever newer lines this build found.
 *
 * Only ever adds: a build that sees less history than the committed file --
 * every Vercel build does -- must not drop the older entries it cannot see.
 * Lines already listed are recognised by their words rather than their date,
 * because the two sources can disagree about the day a late-night commit
 * was made.
 */
export function mergeEntries(found: ChangeEntry[], committed: ChangeEntry[]): ChangeEntry[] {
  const known = new Set(committed.map(keyOf));
  const fresh = found.filter((e) => !known.has(keyOf(e)));
  // Stable, so the order within a day is the order the commits were made.
  return [...fresh, ...committed].sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
}

/** The source of changelog.generated.ts. */
export function renderGenerated(entries: ChangeEntry[]): string {
  const version = entries[0]?.date.replace(/-/g, '.') ?? '0000.00.00';
  const lines = entries
    .map(
      (e) =>
        `  {\n` +
        `    date: ${JSON.stringify(e.date)},\n` +
        `    kind: ${JSON.stringify(e.kind)},\n` +
        `    th: ${JSON.stringify(e.th)},\n` +
        `    en: ${JSON.stringify(e.en)},\n` +
        `  },`
    )
    .join('\n');

  return `/**
 * Generated by scripts/build-changelog.ts from the commits on master.
 *
 * Do not edit: run \`npm run changelog\`. To change what a line says, write a
 * \`Changelog-TH:\` trailer on the commit and regenerate.
 */

import type { ChangeEntry } from './changelog';

export const GENERATED_VERSION = '${version}';

export const GENERATED_CHANGELOG: ChangeEntry[] = [
${lines}
];
`;
}
