/**
 * Generated by scripts/build-changelog.ts from the commits on master.
 *
 * Do not edit: run `npm run changelog`. To change what a line says, write a
 * `Changelog-TH:` trailer on the commit and regenerate.
 */

import type { ChangeEntry } from './changelog';

export const GENERATED_VERSION = '2026.09.20';

export const GENERATED_CHANGELOG: ChangeEntry[] = [
  {
    date: "2026-09-20",
    kind: "new",
    th: "คนรับผิดชอบสัปดาห์ถัดไปกับหน้าหัวข้อนำเสนอเปลี่ยนอัตโนมัติ 1 วันหลังประชุมจบ ไม่ต้องรอแอดมินกดยืนยัน",
    en: "the rotation confirms itself a day after the meeting",
  },
  {
    date: "2026-09-20",
    kind: "new",
    th: "เพิ่มกุญแจอ่านอย่างเดียวสำหรับ /api/cron ใช้กับ automation นอกแล็บได้อย่างปลอดภัย",
    en: "a read-only key for the cron endpoint",
  },
  {
    date: "2026-09-20",
    kind: "fix",
    th: "เข้าสู่ระบบด้วย Google ที่ล้มเหลวจะบอกสาเหตุ และไม่ล้มเพราะชีตติดขัดชั่วคราว",
    en: "a Google sign-in that fails says why, and survives a busy sheet",
  },
  {
    date: "2026-09-19",
    kind: "new",
    th: "the cron endpoint can hand out the open feedback",
    en: "the cron endpoint can hand out the open feedback",
  },
  {
    date: "2026-09-19",
    kind: "new",
    th: "รายการ \"มีอะไรใหม่\" สร้างจาก commit อัตโนมัติแล้ว",
    en: "the changelog writes itself from the commits",
  },
  {
    date: "2026-09-19",
    kind: "new",
    th: "the sidebar says which version this is, and holds its footer",
    en: "the sidebar says which version this is, and holds its footer",
  },
  {
    date: "2026-09-19",
    kind: "new",
    th: "an admin can grant one ability to one person",
    en: "an admin can grant one ability to one person",
  },
  {
    date: "2026-09-19",
    kind: "new",
    th: "an empty calendar means free, and the advisors are not polled",
    en: "an empty calendar means free, and the advisors are not polled",
  },
  {
    date: "2026-09-19",
    kind: "new",
    th: "the week says who is arranging it, and a block opens in a dialog",
    en: "the week says who is arranging it, and a block opens in a dialog",
  },
  {
    date: "2026-09-19",
    kind: "new",
    th: "a free block opens into the hours you can actually book",
    en: "a free block opens into the hours you can actually book",
  },
  {
    date: "2026-09-19",
    kind: "new",
    th: "the availability grid says free, busy or booked, in blocks",
    en: "the availability grid says free, busy or booked, in blocks",
  },
  {
    date: "2026-09-19",
    kind: "new",
    th: "an advisor can take back work as well as set it",
    en: "an advisor can take back work as well as set it",
  },
  {
    date: "2026-09-19",
    kind: "fix",
    th: "a meeting stops announcing an hour it is no longer at",
    en: "a meeting stops announcing an hour it is no longer at",
  },
  {
    date: "2026-09-19",
    kind: "new",
    th: "an advisor directs the work and no longer runs the week",
    en: "an advisor directs the work and no longer runs the week",
  },
  {
    date: "2026-09-19",
    kind: "fix",
    th: "scrolling the week no longer paints a time selection",
    en: "scrolling the week no longer paints a time selection",
  },
  {
    date: "2026-09-19",
    kind: "fix",
    th: "a tap opens somebody else's block, as a click already did",
    en: "a tap opens somebody else's block, as a click already did",
  },
  {
    date: "2026-09-19",
    kind: "fix",
    th: "marking yourself busy works again over an hour somebody else has taken",
    en: "marking yourself busy works again over an hour somebody else has taken",
  },
  {
    date: "2026-09-19",
    kind: "new",
    th: "the advisor arranges the running order, and the order says who did",
    en: "the advisor arranges the running order, and the order says who did",
  },
  {
    date: "2026-09-18",
    kind: "fix",
    th: "pale blue lines stop glowing in the dark theme (#66)",
    en: "pale blue lines stop glowing in the dark theme (#66)",
  },
  {
    date: "2026-09-18",
    kind: "fix",
    th: "every hover in the dark theme now shows, and none vanishes (#65)",
    en: "every hover in the dark theme now shows, and none vanishes (#65)",
  },
  {
    date: "2026-09-18",
    kind: "fix",
    th: "footer links no longer vanish under the pointer in the dark theme (#64)",
    en: "footer links no longer vanish under the pointer in the dark theme (#64)",
  },
  {
    date: "2026-09-18",
    kind: "new",
    th: "the presentations board speaks the dashboard's language",
    en: "the presentations board speaks the dashboard's language",
  },
  {
    date: "2026-09-18",
    kind: "new",
    th: "the running order shows the number instead of describing it",
    en: "the running order shows the number instead of describing it",
  },
  {
    date: "2026-09-18",
    kind: "fix",
    th: "sending a meeting to Google, and recording it, belong to the week's lead",
    en: "sending a meeting to Google, and recording it, belong to the week's lead",
  },
  {
    date: "2026-09-18",
    kind: "fix",
    th: "an admin account is not asked to a meeting it is not counted in",
    en: "an admin account is not asked to a meeting it is not counted in",
  },
  {
    date: "2026-09-18",
    kind: "new",
    th: "the week's controls sit under the meeting, and a professor can reach them",
    en: "the week's controls sit under the meeting, and a professor can reach them",
  },
  {
    date: "2026-09-18",
    kind: "new",
    th: "somebody waiting for approval is asked about first",
    en: "somebody waiting for approval is asked about first",
  },
  {
    date: "2026-09-18",
    kind: "new",
    th: "the dashboard leads with the meeting",
    en: "the dashboard leads with the meeting",
  },
  {
    date: "2026-09-18",
    kind: "fix",
    th: "a meeting with no Meet link stops linking to \"undefined\"",
    en: "a meeting with no Meet link stops linking to \"undefined\"",
  },
  {
    date: "2026-09-18",
    kind: "new",
    th: "every entry on the calendar opens, and the drag waits 200ms",
    en: "every entry on the calendar opens, and the drag waits 200ms",
  },
  {
    date: "2026-09-18",
    kind: "new",
    th: "a calendar filter that actually leaves you your own week",
    en: "a calendar filter that actually leaves you your own week",
  },
  {
    date: "2026-09-17",
    kind: "new",
    th: "an admin can look through the week lead's eyes",
    en: "an admin can look through the week lead's eyes",
  },
  {
    date: "2026-09-17",
    kind: "new",
    th: "a time is agreed, not assumed",
    en: "a time is agreed, not assumed",
  },
  {
    date: "2026-09-17",
    kind: "new",
    th: "the dashboard answers what you came to it for",
    en: "the dashboard answers what you came to it for",
  },
  {
    date: "2026-09-17",
    kind: "fix",
    th: "the hour line reads as an hour again",
    en: "the hour line reads as an hour again",
  },
  {
    date: "2026-09-17",
    kind: "new",
    th: "an admin can look at the app as a professor or a student",
    en: "an admin can look at the app as a professor or a student",
  },
  {
    date: "2026-09-17",
    kind: "new",
    th: "a picture with your feedback, stored on the lab's Drive",
    en: "a picture with your feedback, stored on the lab's Drive",
  },
  {
    date: "2026-09-17",
    kind: "new",
    th: "half-hour slots, and a booked meeting you can move",
    en: "half-hour slots, and a booked meeting you can move",
  },
  {
    date: "2026-09-17",
    kind: "fix",
    th: "a second save writes the newer answer instead of being dropped",
    en: "a second save writes the newer answer instead of being dropped",
  },
  {
    date: "2026-09-17",
    kind: "fix",
    th: "a disconnected calendar stops being read, and a sheet behind the code says so",
    en: "a disconnected calendar stops being read, and a sheet behind the code says so",
  },
  {
    date: "2026-09-17",
    kind: "fix",
    th: "the lint step passes again after the stability PR",
    en: "the lint step passes again after the stability PR",
  },
  {
    date: "2026-09-17",
    kind: "fix",
    th: "stability and performance improvements (#41)",
    en: "stability and performance improvements (#41)",
  },
  {
    date: "2026-09-15",
    kind: "fix",
    th: "three stages on the board",
    en: "three stages on the board",
  },
  {
    date: "2026-09-15",
    kind: "new",
    th: "the week's lead can clear work too",
    en: "the week's lead can clear work too",
  },
  {
    date: "2026-09-15",
    kind: "fix",
    th: "give the calendar page back the space above the calendar",
    en: "give the calendar page back the space above the calendar",
  },
];
