/**
 * Write the changelog the sidebar shows, from the commits on master.
 *
 * Keeping the list by hand meant it was accurate on the day somebody
 * remembered and stale after that. The commits already say what shipped, in
 * order, with dates -- this reads them.
 *
 * Two rules make the result worth reading rather than merely automatic:
 *
 * - Only `feat:` and `fix:` appear. A `docs:`, `chore:`, `test:` or `refactor:`
 *   commit changed nothing the lab can see, and a list padded with those is
 *   one nobody opens twice.
 * - The Thai line comes from a `Changelog-TH:` trailer on the commit. English
 *   commit subjects are written for whoever reads the diff; the sidebar is
 *   read by the lab. A commit with no trailer falls back to its subject, so
 *   the entry still appears -- in English, which is the nudge to add one.
 *
 * Run before shipping -- see DEPLOY.md. The output is committed, because
 * Vercel builds from a shallow clone with no history to read.
 *
 *   npm run changelog -- --check   # say whether the file is out of date
 *   npm run changelog              # rewrite it
 *
 * `--check` is deliberately not a CI step. CI runs on the merge commit of a
 * pull request, whose first parent is master, so the branch's own commits are
 * not in its history and every new entry would read as drift.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = join(process.cwd(), 'src', 'lib', 'changelog.generated.ts');

/** How many commits back to look. Far more than the sidebar shows. */
const DEPTH = 300;

// Unit and record separators, as characters rather than literal bytes in
// this file: git writes them through its own `%x1f` / `%x1e` escapes in the
// format string, because Node refuses an argv entry containing a NUL and a
// raw control byte in source does not survive every editor.
const SEP = String.fromCharCode(31);
const RECORD = String.fromCharCode(30);

type Entry = { date: string; kind: 'new' | 'fix'; th: string; en: string };

function gitLog(): string {
  return execFileSync(
    'git',
    [
      'log',
      // --first-parent so a branch reads as the line of releases it will
      // become once rebased, and HEAD rather than master so a change is in
      // the list on the release that ships it, not the one after.
      '--first-parent',
      'HEAD',
      '--date=short',
      '--pretty=format:%ad%x1f%s%x1f%b%x1e',
      `-n`,
      String(DEPTH),
    ],
    { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 }
  );
}

/** The `Changelog-TH:` trailer, if the commit carries one. */
function thaiTrailer(body: string): string {
  for (const line of body.split('\n')) {
    const match = /^Changelog-TH:\s*(.+?)\s*$/.exec(line);
    if (match) return match[1];
  }
  return '';
}

function parse(log: string): Entry[] {
  const entries: Entry[] = [];

  for (const record of log.split(RECORD)) {
    const [date, subject, body = ''] = record.replace(/^\n+/, '').split(SEP);
    if (!date || !subject) continue;

    // `feat!:` is still a feature as far as the lab is concerned.
    const match = /^(feat|fix)!?:\s*(.+)$/.exec(subject.trim());
    if (!match) continue;

    const [, type, text] = match;
    const th = thaiTrailer(body);
    entries.push({
      date,
      kind: type === 'feat' ? 'new' : 'fix',
      th: th || text,
      en: text,
    });
  }

  return entries;
}

function render(entries: Entry[]): string {
  const version = entries[0]?.date.replace(/-/g, '.') ?? '0000.00.00';
  const lines = entries
    .map(
      (e) =>
        `  {\n` +
        `    date: ${JSON.stringify(e.date)},\n` +
        `    kind: ${JSON.stringify(e.kind)},\n` +
        `    th: ${JSON.stringify(e.th)},\n` +
        `    en: ${JSON.stringify(e.en)},\n` +
        `  },`
    )
    .join('\n');

  return `/**
 * Generated by scripts/build-changelog.ts from the commits on master.
 *
 * Do not edit: run \`npm run changelog\`. To change what a line says, write a
 * \`Changelog-TH:\` trailer on the commit and regenerate.
 */

import type { ChangeEntry } from './changelog';

export const GENERATED_VERSION = '${version}';

export const GENERATED_CHANGELOG: ChangeEntry[] = [
${lines}
];
`;
}

function main() {
  const wanted = render(parse(gitLog()));

  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(OUT, 'utf8');
    } catch {
      // Missing counts as out of date.
    }
    if (current !== wanted) {
      console.error(
        'changelog.generated.ts is out of date. Run `npm run changelog` and commit the result.'
      );
      process.exit(1);
    }
    console.log('Changelog is up to date.');
    return;
  }

  writeFileSync(OUT, wanted, 'utf8');
  const count = (wanted.match(/date: /g) ?? []).length;
  console.log(`Wrote ${count} entries to src/lib/changelog.generated.ts`);
}

main();
